/**
 * Default report template seed data.
 */
import type { ReportSection, ReportStyling } from '../../types/report-template.js';

export const DEFAULT_TEMPLATE_ID = '00000000-0000-0000-0000-000000000001';

export const DEFAULT_SECTIONS: ReportSection[] = [
  {
    id: 'section-summary',
    type: 'summary',
    title: 'Summary',
    enabled: true,
    order: 1,
  },
  {
    id: 'section-steps',
    type: 'steps',
    title: 'Steps',
    enabled: true,
    order: 2,
  },
  {
    id: 'section-screenshots',
    type: 'screenshots',
    title: 'Screenshots',
    enabled: true,
    order: 3,
  },
  {
    id: 'section-errors',
    type: 'errors',
    title: 'Errors',
    enabled: true,
    order: 4,
  },
  {
    id: 'section-performance',
    type: 'performance',
    title: 'Performance',
    enabled: true,
    order: 5,
  },
  {
    id: 'section-suggestions',
    type: 'suggestions',
    title: 'Suggestions',
    enabled: true,
    order: 6,
  },
  {
    id: 'section-raw',
    type: 'raw',
    title: 'Raw Data',
    enabled: false,
    order: 7,
  },
];

export const DEFAULT_STYLING: ReportStyling = {
  theme: 'light',
  primaryColor: '#3b82f6',
  footerText: 'Generated by ElectronHound',
};

export const DEFAULT_TEMPLATE = {
  id: DEFAULT_TEMPLATE_ID,
  name: 'Default',
  description: 'The default ElectronHound report template with standard sections.',
  sections: DEFAULT_SECTIONS,
  styling: DEFAULT_STYLING,
  isDefault: true,
};
